name = "dota-matches-api"
account_id = "19a745c88f8264f29c608584b7e417ab"
compatibility_date = "2022-07-17"
usage_model = "bundled"

# triggers = {crons = ["0 9 * * *"]}
kv_namespaces = [{binding = "CACHE", id = "ef6e3ce520544b088a26a00f1b27404a"}]
# r2_buckets = [{ binding = "WEBHOOKS", bucket_name = "dota-matches-webhooks" }]

[miniflare]
kv_persist = true
r2_persist = false

[vars]
API_BASE = "https://dota-matches-api.beequeue.workers.dev"
DISCORD_CLIENT_ID = "999099490273337354"
DISCORD_PUBLIC_KEY = "7df58ea4839882888b45f9b56936b0e5e2f6f49fe1d0e88d2637cb4e14ce849c"

[build]
command = "pnpm --silent build"
# The directory to watch for changes while using `wrangler dev`, defaults to the current working directory
watch_dir = "src"
[build.upload]
format = "modules"
main = "index.mjs"
